name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      working-directory: backend
    
    - name: Run backend tests
      env:
        NODE_ENV: test
        JWT_SECRET: test-secret
        BACKEND_URL: http://localhost:3000
        DEFAULT_ADMIN_IN_DEV: true
        # Optional variables for test environment
        SLACK_BOT_TOKEN: xoxb-test-token
        SLACK_ADMIN_EMAIL: test@example.com
        GOOGLE_CLIENT_ID: test-client-id
        GOOGLE_CLIENT_SECRET: test-client-secret
      run: npm test
      working-directory: backend
    
    - name: Upload backend test coverage
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage-report
        path: backend/coverage/
        
  frontend-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      working-directory: frontend
    
    - name: Run frontend tests
      run: npm test
      working-directory: frontend
    
    - name: Upload frontend test coverage
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage-report
        path: frontend/coverage/ 